eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE: localhost:8761/eureka}
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost:8761}
